### ISSUE TITLE
Demo of gatsby-remark-images-anywhere with a gatsby-transformer-remark custom component for gatsby-image like features

### ISSUE THREAD

**Issue by fartinmartin** [d4rekanguok/gatsby-remark-images-anywhere#2]
I have created a [CodeSandbox](https://codesandbox.io/s/gatsby-remark-images-anywhere-remark-custom-component-lazy-load-007vo) which demos how `gatsby-remark-images-anywhere` could work with a [`gatsby-transformer-remark` custom component](https://using-remark.gatsbyjs.org/custom-components/) to achieve `gatsby-image` like benefits. It's not complete, but includes aspect ratio padding, lazy loading, and the blur up effect.

**Comment by d4rekanguok** [comment]
Wow, thank you for this!! 🙏 I'll add this to the readme.

I was looking to implement this with a more vanilla approach (without using remark custom component). Would you be interested in converting this into a PR? Otherwise this'd serve as a great starting point for me, so thank you again!

**Comment by fartinmartin** [comment]
Hey, thank you—I'm glad you like this! I'd love to convert this to a PR, but I'm not super confident in my JavaScript/Gatsby/Node knowledge to be able to implement it within your plugin 😬 

I appreciate all the work you've put into this plugin! Please feel free to use this however you wish!

**Comment by d4rekanguok** [comment]
Nice! If you are interested, just send over whatever you have & then we can work together to get it in shape. You went so far as using a custom component, and I've seen the codesandbox so I have no doubt in your js/gatsby skill!

I've been wanting to spit this [line out into its own file](https://github.com/d4rekanguok/gatsby-remark-images-anywhere/blob/581cf5766596635c8ca8d9470a77b9237f7a5686/src/index.ts#L8), beef up the markup + a few unique classnames, then add a [onClientEntry](https://www.gatsbyjs.org/docs/browser-apis/#onClientEntry) hook in a `gatsby-browser.ts` file to add stuff like blur up etc.

I've just set up a gitter for this project so feel free to ping me any time you'd like!

**Comment by fartinmartin** [comment]
Awesome! That's actually a helpful starting point. I'll definitely be asking you questions about onClientEntry if/when it comes to that, haha. Thanks for including me on this, it's already been educational experience!

I do have one thought about markup: is it possible (or desirable) to have `gatsby-image` generate markup within your plugin? I was trying out [another plugin](https://www.jamessimone.net/blog/image-optimization-with-gatsby) before this (it wasn't working with my site, we tried debugging [over on reddit](https://www.reddit.com/r/reactjs/comments/bwcd9y/optimizing_remote_images_with_gatsby/ezr1r7q/) if you're interested) and it seems like that's how the author was getting his markup.

**Comment by d4rekanguok** [comment]
Oh that's a nice article, it makes me realize I haven't put in place any consideration for .svg and .gif files!! I feel like you came really close in the reddit thread though... but I'm glad that this plugin works out for you!

On using gatsby-image to generate markup, my gut reaction is that it is simpler to create markup manually, since I think there's no easy way to rehydrate gatsby-image on the browser side.

Also, I think gatsby-image tackles a slightly different challenge. For example I don't think feature like art direction is nearly as important for a image inside a markdown article, while the ability to open an image in a lightbox is not as important for header images (typically use gatsby-image).

For this plugin, I plan to have a stable set of features (blur up / fade in, lazy loading, lightbox) that satisfy most basic use cases while allow users total flexibility to implement their own features. However I'm also inexperienced so I'm not sure how that'll pan out 😅

**Comment by fartinmartin** [comment]
Yes! That article was super informative for me even though it didn't work out for my site. Glad you got something out of it too—SVG and GIF support would be awesome 😀

Great points about markdown images vs. `gatsby-images`—I'm sold, haha! And I'm really interested in the lightbox feature. It sounds like a lot, but those are good goals and I have total faith in you!

I do have some additional questions, but I think I'll post them to the gitter!
